name: WakaTime Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    if: github.repository_owner == 'SerenModz21' # shouldn't be running on forks
    name: Update Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: SerenModz21/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MSG: ":memo: Updated with Dev Metrics"
          SHOW_OS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
