name: WakaTime Gist Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update:
    if: github.repository_owner == 'SerenModz21' # shouldn't be running on forks
    name: Update Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 78d648b5c978d2b30f568ee112561c13
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
